[tool.black]
line-length = 79
target-version = ["py311"]
exclude = ["**/venv/*", "**/.mypy_cache/*", "**/tests/*"]
skip-string-normalization = true

[tool.mypy]
python_version = 3.11
show_error_codes = true
warn_redundant_casts = true
warn_unused_ignores = true
exclude = "venv|tests|.mypy_cache"
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_return_any = true
implicit_reexport = false
strict_equality = true
